### ISSUE TITLE
[2pts] Database setup

### ISSUE THREAD

**Issue by karungar** [karungar/deploy-a-static-website-to-S3#1]
# Task Details

- [ ] Create a DynamoDB table

    - Name the table Resumes 
    - Specify the partition key  as ' id' and data type as 'string'

- [ ] Upload the resume document into an Amazon S3 bucket in the DynamoDB JSON format
- [ ] Import the DynamoDB JSON resume document from Amazon S3
